## RevolutionDCM Mod Code - Memory Optimized for 32-bit Python 2.4
##
## This code uses the BUG standard to control RevolutionDCM options.
## RevolutionDCM.ini is generated by BUG and is the repository of all option states.
## Options are passed to the SDK via python calls that modify GlobalDefinesAlt.xml.
##
## Copyright (c) 2007-2008 The BUG Mod.
## Author: Glider1
## Optimized for 32-bit memory constraints

from CvPythonExtensions import *
import BugOptions
import BugCore

# Single global context reference to reduce lookups
GC = CyGlobalContext()
# Lazy initialization of RevDCMOpt to save memory
RevDCMOpt = None


def _getRevDCMOpt():
    """Lazy getter for RevDCMOpt to ensure it's initialized when needed"""
    global RevDCMOpt
    if RevDCMOpt is None:
        RevDCMOpt = BugCore.game.RevDCM
    return RevDCMOpt


# Use constants instead of strings to reduce memory
# Define option indices for faster access
DCM_RANGE_BOMBARD = 0
DCM_OPP_FIRE = 1
DCM_AIR_BOMBING = 2
DCM_ACTIVE_DEFENSE = 3
DCM_FIGHTER_ENGAGE = 4
IDW_ENABLED = 5
IDW_EMERGENCY_DRAFT_ENABLED = 6
IDW_NO_BARBARIAN_INFLUENCE = 7
IDW_NO_NAVAL_INFLUENCE = 8
IDW_PILLAGE_INFLUENCE_ENABLED = 9
SS_ENABLED = 10
SS_BRIBE = 11
SS_ASSASSINATE = 12
OC_RESPAWN_HOLY_CITIES = 13
LIMITED_RELIGIONS_EXCEPTIONS = 14
SHOW_HIDDEN_ATTITUDE = 15
DYNAMIC_CIV_NAMES = 16

# Pre-define option mapping to reduce memory allocations
# Using tuples (immutable) instead of lists for memory efficiency
OPTION_MAP = (
    ("DCM_RANGE_BOMBARD", "isDCM_RANGE_BOMBARD"),
    ("DCM_OPP_FIRE", "isDCM_OPP_FIRE"),
    ("DCM_AIR_BOMBING", "isDCM_AIR_BOMBING"),
    ("DCM_ACTIVE_DEFENSE", "isDCM_ACTIVE_DEFENSE"),
    ("DCM_FIGHTER_ENGAGE", "isDCM_FIGHTER_ENGAGE"),
    ("IDW_ENABLED", "isIDW_ENABLED"),
    ("IDW_EMERGENCY_DRAFT_ENABLED", "isIDW_EMERGENCY_DRAFT_ENABLED"),
    ("IDW_NO_BARBARIAN_INFLUENCE", "isIDW_NO_BARBARIAN_INFLUENCE"),
    ("IDW_NO_NAVAL_INFLUENCE", "isIDW_NO_NAVAL_INFLUENCE"),
    ("IDW_PILLAGE_INFLUENCE_ENABLED", "isIDW_PILLAGE_INFLUENCE_ENABLED"),
    ("SS_ENABLED", "isSS_ENABLED"),
    ("SS_BRIBE", "isSS_BRIBE"),
    ("SS_ASSASSINATE", "isSS_ASSASSINATE"),
    ("OC_RESPAWN_HOLY_CITIES", "isOC_RESPAWN_HOLY_CITIES"),
    ("LIMITED_RELIGIONS_EXCEPTIONS", "isLIMITED_RELIGIONS_EXCEPTIONS"),
    ("SHOW_HIDDEN_ATTITUDE", "isHiddenAttitude"),
)


class RevDCM:
    # Use __slots__ to reduce memory overhead per instance
    __slots__ = ()

    def __init__(self, eventManager):
        # Register event handlers
        eventManager.addEventHandler("OnLoad", self.optionUpdate)
        eventManager.addEventHandler("GameStart", self.optionUpdate)

    def optionUpdate(self, argsList=None):
        """Unified option update handler"""
        game = GC.getGame()
        opt = _getRevDCMOpt()
        if game.isNetworkMultiPlayer() or opt.isReset():
            resetOptions()
        else:
            setXMLOptionsfromIniFile()


# Generic change handler to replace individual functions
def genericChangeHandler(optionIndex):
    """Generic handler for option changes"""
    if optionIndex < len(OPTION_MAP):
        xml_name, method_name = OPTION_MAP[optionIndex]
        opt = _getRevDCMOpt()
        method = getattr(opt, method_name)
        GC.setDefineINT(xml_name, method())
    return True


# Module level functions
def changedReset(option, value):
    resetOptions()
    return True


# Replace individual change handlers with lambda functions that call generic handler
# This reduces code duplication and memory usage
changedDCM_RANGE_BOMBARD = lambda o, v: genericChangeHandler(DCM_RANGE_BOMBARD)
changedDCM_OPP_FIRE = lambda o, v: genericChangeHandler(DCM_OPP_FIRE)
changedDCM_AIR_BOMBING = lambda o, v: genericChangeHandler(DCM_AIR_BOMBING)
changedDCM_ACTIVE_DEFENSE = lambda o, v: genericChangeHandler(DCM_ACTIVE_DEFENSE)
changedDCM_FIGHTER_ENGAGE = lambda o, v: genericChangeHandler(DCM_FIGHTER_ENGAGE)
changedIDW_ENABLED = lambda o, v: genericChangeHandler(IDW_ENABLED)
changedIDW_EMERGENCY_DRAFT_ENABLED = lambda o, v: genericChangeHandler(IDW_EMERGENCY_DRAFT_ENABLED)
changedIDW_NO_BARBARIAN_INFLUENCE = lambda o, v: genericChangeHandler(IDW_NO_BARBARIAN_INFLUENCE)
changedIDW_NO_NAVAL_INFLUENCE = lambda o, v: genericChangeHandler(IDW_NO_NAVAL_INFLUENCE)
changedIDW_PILLAGE_INFLUENCE_ENABLED = lambda o, v: genericChangeHandler(IDW_PILLAGE_INFLUENCE_ENABLED)
changedSS_ENABLED = lambda o, v: genericChangeHandler(SS_ENABLED)
changedSS_BRIBE = lambda o, v: genericChangeHandler(SS_BRIBE)
changedSS_ASSASSINATE = lambda o, v: genericChangeHandler(SS_ASSASSINATE)
changedOC_RESPAWN_HOLY_CITIES = lambda o, v: genericChangeHandler(OC_RESPAWN_HOLY_CITIES)
changedLIMITED_RELIGIONS_EXCEPTIONS = lambda o, v: genericChangeHandler(LIMITED_RELIGIONS_EXCEPTIONS)
changedHiddenAttitude = lambda o, v: genericChangeHandler(SHOW_HIDDEN_ATTITUDE)


def changedDYNAMIC_CIV_NAMES(option, value):
    """Handle dynamic civ names separately due to special logic"""
    import DynamicCivNames
    if value:
        DynamicCivNames.init()
    else:
        DynamicCivNames.uninit()


def setXMLOptionsfromIniFile():
    """Set all XML options from ini file - optimized version"""
    # Note: Removed print statement to save memory in production
    # Add back if debugging needed: print "Reinitialising RevDCM SDK variables"

    # Cache setDefineINT method reference to avoid repeated lookups
    setDefine = GC.setDefineINT
    opt = _getRevDCMOpt()

    # Process all standard options in a single loop
    for xml_name, method_name in OPTION_MAP:
        method = getattr(opt, method_name)
        setDefine(xml_name, method())

    # Handle special case for LIMITED_RELIGIONS_EXCEPTIONS
    setDefine("LIMITED_RELIGIONS_EXCEPTIONS", 0)

    # Handle dynamic civ names
    changedDYNAMIC_CIV_NAMES(None, opt.isDYNAMIC_CIV_NAMES())


def resetOptions():
    """Reset all options to default values"""
    # Get options once to avoid repeated lookups
    options = BugOptions.getOptions

    # Cache options lists
    revDCMoptions = options("RevDCM").options
    revolutionOptions = options("Revolution").options
    actionOptions = options("Actions").options

    # Reset all options using more efficient iteration
    for optionList in (revDCMoptions, revolutionOptions, actionOptions):
        for option in optionList:
            option.resetValue()

    # Update XML settings
    setXMLOptionsfromIniFile()

    # Reset the reset flag
    opt = _getRevDCMOpt()
    opt.setReset(False)